#############################################################################
# Makefile for building: ik
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  ik.pro
# Template: app
# Command: /usr/lib/qt/bin/qmake -spec linux-clang -o Makefile ik.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = @echo compiling $< && clang
CXX           = @echo compiling $< && clang++
DEFINES       = -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -Werror -g -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/qt -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -I.moc -I/usr/lib/qt/mkspecs/linux-clang
QMAKE         = /usr/lib/qt/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ik1.0.0
DISTDIR = /home/stephan/Dokumente/BA/demo/.obj/ik1.0.0
LINK          = @echo linking $@ && clang++
LFLAGS        = -ccc-gcc-name g++
LIBS          = $(SUBLIBS) -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = .obj/

####### Files

SOURCES       = src/core.cpp \
		src/IKWidget.cpp \
		src/Joint.cpp \
		src/KinematicChain.cpp \
		src/Window.cpp \
		src/AnalyticIK.cpp \
		src/JacobianIK.cpp \
		src/JacobianPseudoIK.cpp \
		src/FABRIK.cpp .moc/moc_IKWidget.cpp \
		.moc/moc_Window.cpp
OBJECTS       = .obj/core.o \
		.obj/IKWidget.o \
		.obj/Joint.o \
		.obj/KinematicChain.o \
		.obj/Window.o \
		.obj/AnalyticIK.o \
		.obj/JacobianIK.o \
		.obj/JacobianPseudoIK.o \
		.obj/FABRIK.o \
		.obj/moc_IKWidget.o \
		.obj/moc_Window.o
DIST          = /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/clang.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_Attica.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt/mkspecs/modules/qt_KParts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_enginio.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_enginio_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/qt/mkspecs/modules/qt_QGpgme.pri \
		/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-clang/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		/usr/lib/qt/mkspecs/features/silent.prf \
		ik.pro src/IKWidget.hpp \
		src/Joint.hpp \
		src/KinematicChain.hpp \
		src/Window.hpp \
		src/AnalyticIK.hpp \
		src/JacobianIK.hpp \
		src/JacobianPseudoIK.hpp \
		src/FABRIK.hpp src/core.cpp \
		src/IKWidget.cpp \
		src/Joint.cpp \
		src/KinematicChain.cpp \
		src/Window.cpp \
		src/AnalyticIK.cpp \
		src/JacobianIK.cpp \
		src/JacobianPseudoIK.cpp \
		src/FABRIK.cpp
QMAKE_TARGET  = ik
DESTDIR       = 
TARGET        = ik


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ik.pro /usr/lib/qt/mkspecs/linux-clang/qmake.conf /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/clang.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_Attica.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt/mkspecs/modules/qt_KParts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_enginio.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_enginio_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/qt/mkspecs/modules/qt_QGpgme.pri \
		/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-clang/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		/usr/lib/qt/mkspecs/features/silent.prf \
		ik.pro \
		/lib/libQt5Widgets.prl \
		/lib/libQt5Gui.prl \
		/lib/libQt5Core.prl
	$(QMAKE) -spec linux-clang -o Makefile ik.pro
/usr/lib/qt/mkspecs/features/spec_pre.prf:
/usr/lib/qt/mkspecs/common/unix.conf:
/usr/lib/qt/mkspecs/common/linux.conf:
/usr/lib/qt/mkspecs/common/sanitize.conf:
/usr/lib/qt/mkspecs/common/gcc-base.conf:
/usr/lib/qt/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt/mkspecs/common/clang.conf:
/usr/lib/qt/mkspecs/qconfig.pri:
/usr/lib/qt/mkspecs/modules/qt_Attica.pri:
/usr/lib/qt/mkspecs/modules/qt_KActivities.pri:
/usr/lib/qt/mkspecs/modules/qt_KArchive.pri:
/usr/lib/qt/mkspecs/modules/qt_KAuth.pri:
/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri:
/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri:
/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri:
/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KCrash.pri:
/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri:
/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri:
/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KI18n.pri:
/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri:
/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri:
/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri:
/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri:
/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri:
/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri:
/usr/lib/qt/mkspecs/modules/qt_KParts.pri:
/usr/lib/qt/mkspecs/modules/qt_KService.pri:
/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri:
/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KWallet.pri:
/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri:
/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dcore.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dextras.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dinput.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3drender.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_enginio.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_enginio_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_nfc.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_serialbus.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri:
/usr/lib/qt/mkspecs/modules/qt_QGpgme.pri:
/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_Solid.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri:
/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri:
/usr/lib/qt/mkspecs/features/qt_functions.prf:
/usr/lib/qt/mkspecs/features/qt_config.prf:
/usr/lib/qt/mkspecs/linux-clang/qmake.conf:
/usr/lib/qt/mkspecs/features/spec_post.prf:
/usr/lib/qt/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt/mkspecs/features/default_pre.prf:
/usr/lib/qt/mkspecs/features/resolve_config.prf:
/usr/lib/qt/mkspecs/features/default_post.prf:
/usr/lib/qt/mkspecs/features/warn_on.prf:
/usr/lib/qt/mkspecs/features/qt.prf:
/usr/lib/qt/mkspecs/features/resources.prf:
/usr/lib/qt/mkspecs/features/moc.prf:
/usr/lib/qt/mkspecs/features/unix/opengl.prf:
/usr/lib/qt/mkspecs/features/uic.prf:
/usr/lib/qt/mkspecs/features/unix/thread.prf:
/usr/lib/qt/mkspecs/features/file_copies.prf:
/usr/lib/qt/mkspecs/features/testcase_targets.prf:
/usr/lib/qt/mkspecs/features/exceptions.prf:
/usr/lib/qt/mkspecs/features/yacc.prf:
/usr/lib/qt/mkspecs/features/lex.prf:
/usr/lib/qt/mkspecs/features/silent.prf:
ik.pro:
/lib/libQt5Widgets.prl:
/lib/libQt5Gui.prl:
/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-clang -o Makefile ik.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents src/IKWidget.hpp src/Joint.hpp src/KinematicChain.hpp src/Window.hpp src/AnalyticIK.hpp src/JacobianIK.hpp src/JacobianPseudoIK.hpp src/FABRIK.hpp $(DISTDIR)/
	$(COPY_FILE) --parents src/core.cpp src/IKWidget.cpp src/Joint.cpp src/KinematicChain.cpp src/Window.cpp src/AnalyticIK.cpp src/JacobianIK.cpp src/JacobianPseudoIK.cpp src/FABRIK.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: .moc/moc_IKWidget.cpp .moc/moc_Window.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) .moc/moc_IKWidget.cpp .moc/moc_Window.cpp
.moc/moc_IKWidget.cpp: src/KinematicChain.hpp \
		src/Joint.hpp \
		src/IKWidget.hpp \
		/usr/lib/qt/bin/moc
	@echo moc src/IKWidget.hpp && /usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-clang -I/home/stephan/Dokumente/BA/demo -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.1.1/backward -I/usr/local/include -I/usr/lib/clang/3.8.1/include -I/usr/include src/IKWidget.hpp -o .moc/moc_IKWidget.cpp

.moc/moc_Window.cpp: src/Window.hpp \
		/usr/lib/qt/bin/moc
	@echo moc src/Window.hpp && /usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-clang -I/home/stephan/Dokumente/BA/demo -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.1.1/backward -I/usr/local/include -I/usr/lib/clang/3.8.1/include -I/usr/include src/Window.hpp -o .moc/moc_Window.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

.obj/core.o: src/core.cpp src/Window.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/core.o src/core.cpp

.obj/IKWidget.o: src/IKWidget.cpp src/IKWidget.hpp \
		src/KinematicChain.hpp \
		src/Joint.hpp \
		src/AnalyticIK.hpp \
		src/JacobianIK.hpp \
		src/Eigen/Dense \
		src/Eigen/Core \
		src/Eigen/src/Core/util/DisableStupidWarnings.h \
		src/Eigen/src/Core/util/Macros.h \
		src/Eigen/src/Core/util/MKL_support.h \
		src/Eigen/src/Core/util/Constants.h \
		src/Eigen/src/Core/util/ForwardDeclarations.h \
		src/Eigen/src/Core/util/Meta.h \
		src/Eigen/src/Core/util/StaticAssert.h \
		src/Eigen/src/Core/util/XprHelper.h \
		src/Eigen/src/Core/util/Memory.h \
		src/Eigen/src/Core/NumTraits.h \
		src/Eigen/src/Core/MathFunctions.h \
		src/Eigen/src/Core/GenericPacketMath.h \
		src/Eigen/src/Core/arch/SSE/PacketMath.h \
		src/Eigen/src/Core/arch/SSE/MathFunctions.h \
		src/Eigen/src/Core/arch/SSE/Complex.h \
		src/Eigen/src/Core/arch/AltiVec/PacketMath.h \
		src/Eigen/src/Core/arch/AltiVec/Complex.h \
		src/Eigen/src/Core/arch/NEON/PacketMath.h \
		src/Eigen/src/Core/arch/NEON/Complex.h \
		src/Eigen/src/Core/arch/Default/Settings.h \
		src/Eigen/src/Core/Functors.h \
		src/Eigen/src/Core/DenseCoeffsBase.h \
		src/Eigen/src/Core/DenseBase.h \
		src/Eigen/src/plugins/BlockMethods.h \
		src/Eigen/src/Core/MatrixBase.h \
		src/Eigen/src/plugins/CommonCwiseUnaryOps.h \
		src/Eigen/src/plugins/CommonCwiseBinaryOps.h \
		src/Eigen/src/plugins/MatrixCwiseUnaryOps.h \
		src/Eigen/src/plugins/MatrixCwiseBinaryOps.h \
		src/Eigen/src/Core/EigenBase.h \
		src/Eigen/src/Core/Assign.h \
		src/Eigen/src/Core/util/BlasUtil.h \
		src/Eigen/src/Core/DenseStorage.h \
		src/Eigen/src/Core/NestByValue.h \
		src/Eigen/src/Core/ForceAlignedAccess.h \
		src/Eigen/src/Core/ReturnByValue.h \
		src/Eigen/src/Core/NoAlias.h \
		src/Eigen/src/Core/PlainObjectBase.h \
		src/Eigen/src/Core/Matrix.h \
		src/Eigen/src/Core/Array.h \
		src/Eigen/src/Core/CwiseBinaryOp.h \
		src/Eigen/src/Core/CwiseUnaryOp.h \
		src/Eigen/src/Core/CwiseNullaryOp.h \
		src/Eigen/src/Core/CwiseUnaryView.h \
		src/Eigen/src/Core/SelfCwiseBinaryOp.h \
		src/Eigen/src/Core/Dot.h \
		src/Eigen/src/Core/StableNorm.h \
		src/Eigen/src/Core/MapBase.h \
		src/Eigen/src/Core/Stride.h \
		src/Eigen/src/Core/Map.h \
		src/Eigen/src/Core/Block.h \
		src/Eigen/src/Core/VectorBlock.h \
		src/Eigen/src/Core/Ref.h \
		src/Eigen/src/Core/Transpose.h \
		src/Eigen/src/Core/DiagonalMatrix.h \
		src/Eigen/src/Core/Diagonal.h \
		src/Eigen/src/Core/DiagonalProduct.h \
		src/Eigen/src/Core/PermutationMatrix.h \
		src/Eigen/src/Core/Transpositions.h \
		src/Eigen/src/Core/Redux.h \
		src/Eigen/src/Core/Visitor.h \
		src/Eigen/src/Core/Fuzzy.h \
		src/Eigen/src/Core/IO.h \
		src/Eigen/src/Core/Swap.h \
		src/Eigen/src/Core/CommaInitializer.h \
		src/Eigen/src/Core/Flagged.h \
		src/Eigen/src/Core/ProductBase.h \
		src/Eigen/src/Core/GeneralProduct.h \
		src/Eigen/src/Core/TriangularMatrix.h \
		src/Eigen/src/Core/SelfAdjointView.h \
		src/Eigen/src/Core/products/GeneralBlockPanelKernel.h \
		src/Eigen/src/Core/products/Parallelizer.h \
		src/Eigen/src/Core/products/CoeffBasedProduct.h \
		src/Eigen/src/Core/products/GeneralMatrixVector.h \
		src/Eigen/src/Core/products/GeneralMatrixMatrix.h \
		src/Eigen/src/Core/SolveTriangular.h \
		src/Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
		src/Eigen/src/Core/products/SelfadjointMatrixVector.h \
		src/Eigen/src/Core/products/SelfadjointMatrixMatrix.h \
		src/Eigen/src/Core/products/SelfadjointProduct.h \
		src/Eigen/src/Core/products/SelfadjointRank2Update.h \
		src/Eigen/src/Core/products/TriangularMatrixVector.h \
		src/Eigen/src/Core/products/TriangularMatrixMatrix.h \
		src/Eigen/src/Core/products/TriangularSolverMatrix.h \
		src/Eigen/src/Core/products/TriangularSolverVector.h \
		src/Eigen/src/Core/BandMatrix.h \
		src/Eigen/src/Core/CoreIterators.h \
		src/Eigen/src/Core/BooleanRedux.h \
		src/Eigen/src/Core/Select.h \
		src/Eigen/src/Core/VectorwiseOp.h \
		src/Eigen/src/Core/Random.h \
		src/Eigen/src/Core/Replicate.h \
		src/Eigen/src/Core/Reverse.h \
		src/Eigen/src/Core/ArrayBase.h \
		src/Eigen/src/plugins/ArrayCwiseUnaryOps.h \
		src/Eigen/src/plugins/ArrayCwiseBinaryOps.h \
		src/Eigen/src/Core/ArrayWrapper.h \
		src/Eigen/src/Core/products/GeneralMatrixMatrix_MKL.h \
		src/Eigen/src/Core/products/GeneralMatrixVector_MKL.h \
		src/Eigen/src/Core/products/GeneralMatrixMatrixTriangular_MKL.h \
		src/Eigen/src/Core/products/SelfadjointMatrixMatrix_MKL.h \
		src/Eigen/src/Core/products/SelfadjointMatrixVector_MKL.h \
		src/Eigen/src/Core/products/TriangularMatrixMatrix_MKL.h \
		src/Eigen/src/Core/products/TriangularMatrixVector_MKL.h \
		src/Eigen/src/Core/products/TriangularSolverMatrix_MKL.h \
		src/Eigen/src/Core/Assign_MKL.h \
		src/Eigen/src/Core/GlobalFunctions.h \
		src/Eigen/src/Core/util/ReenableStupidWarnings.h \
		src/Eigen/Eigen2Support \
		src/Eigen/src/Eigen2Support/Macros.h \
		src/Eigen/src/Eigen2Support/Memory.h \
		src/Eigen/src/Eigen2Support/Meta.h \
		src/Eigen/src/Eigen2Support/Lazy.h \
		src/Eigen/src/Eigen2Support/Cwise.h \
		src/Eigen/src/Eigen2Support/CwiseOperators.h \
		src/Eigen/src/Eigen2Support/TriangularSolver.h \
		src/Eigen/src/Eigen2Support/Block.h \
		src/Eigen/src/Eigen2Support/VectorBlock.h \
		src/Eigen/src/Eigen2Support/Minor.h \
		src/Eigen/src/Eigen2Support/MathFunctions.h \
		src/Eigen/LU \
		src/Eigen/src/misc/Solve.h \
		src/Eigen/src/misc/Kernel.h \
		src/Eigen/src/misc/Image.h \
		src/Eigen/src/LU/FullPivLU.h \
		src/Eigen/src/LU/PartialPivLU.h \
		src/Eigen/src/LU/PartialPivLU_MKL.h \
		src/Eigen/src/LU/Determinant.h \
		src/Eigen/src/LU/Inverse.h \
		src/Eigen/src/LU/arch/Inverse_SSE.h \
		src/Eigen/src/Eigen2Support/LU.h \
		src/Eigen/Cholesky \
		src/Eigen/src/Cholesky/LLT.h \
		src/Eigen/src/Cholesky/LDLT.h \
		src/Eigen/src/Cholesky/LLT_MKL.h \
		src/Eigen/QR \
		src/Eigen/Jacobi \
		src/Eigen/src/Jacobi/Jacobi.h \
		src/Eigen/Householder \
		src/Eigen/src/Householder/Householder.h \
		src/Eigen/src/Householder/HouseholderSequence.h \
		src/Eigen/src/Householder/BlockHouseholder.h \
		src/Eigen/src/QR/HouseholderQR.h \
		src/Eigen/src/QR/FullPivHouseholderQR.h \
		src/Eigen/src/QR/ColPivHouseholderQR.h \
		src/Eigen/src/QR/HouseholderQR_MKL.h \
		src/Eigen/src/QR/ColPivHouseholderQR_MKL.h \
		src/Eigen/src/Eigen2Support/QR.h \
		src/Eigen/Eigenvalues \
		src/Eigen/Geometry \
		src/Eigen/SVD \
		src/Eigen/src/SVD/JacobiSVD.h \
		src/Eigen/src/SVD/JacobiSVD_MKL.h \
		src/Eigen/src/SVD/UpperBidiagonalization.h \
		src/Eigen/src/Eigen2Support/SVD.h \
		src/Eigen/src/Geometry/OrthoMethods.h \
		src/Eigen/src/Geometry/EulerAngles.h \
		src/Eigen/src/Geometry/Homogeneous.h \
		src/Eigen/src/Geometry/RotationBase.h \
		src/Eigen/src/Geometry/Rotation2D.h \
		src/Eigen/src/Geometry/Quaternion.h \
		src/Eigen/src/Geometry/AngleAxis.h \
		src/Eigen/src/Geometry/Transform.h \
		src/Eigen/src/Geometry/Translation.h \
		src/Eigen/src/Geometry/Scaling.h \
		src/Eigen/src/Geometry/Hyperplane.h \
		src/Eigen/src/Geometry/ParametrizedLine.h \
		src/Eigen/src/Geometry/AlignedBox.h \
		src/Eigen/src/Geometry/Umeyama.h \
		src/Eigen/src/Geometry/arch/Geometry_SSE.h \
		src/Eigen/src/Eigen2Support/Geometry/All.h \
		src/Eigen/src/Eigen2Support/Geometry/RotationBase.h \
		src/Eigen/src/Eigen2Support/Geometry/Rotation2D.h \
		src/Eigen/src/Eigen2Support/Geometry/Quaternion.h \
		src/Eigen/src/Eigen2Support/Geometry/AngleAxis.h \
		src/Eigen/src/Eigen2Support/Geometry/Transform.h \
		src/Eigen/src/Eigen2Support/Geometry/Translation.h \
		src/Eigen/src/Eigen2Support/Geometry/Scaling.h \
		src/Eigen/src/Eigen2Support/Geometry/AlignedBox.h \
		src/Eigen/src/Eigen2Support/Geometry/Hyperplane.h \
		src/Eigen/src/Eigen2Support/Geometry/ParametrizedLine.h \
		src/Eigen/src/Eigenvalues/Tridiagonalization.h \
		src/Eigen/src/Eigenvalues/RealSchur.h \
		src/Eigen/src/Eigenvalues/HessenbergDecomposition.h \
		src/Eigen/src/Eigenvalues/EigenSolver.h \
		src/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h \
		src/Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h \
		src/Eigen/src/Eigenvalues/ComplexSchur.h \
		src/Eigen/src/Eigenvalues/ComplexEigenSolver.h \
		src/Eigen/src/Eigenvalues/RealQZ.h \
		src/Eigen/src/Eigenvalues/GeneralizedEigenSolver.h \
		src/Eigen/src/Eigenvalues/MatrixBaseEigenvalues.h \
		src/Eigen/src/Eigenvalues/RealSchur_MKL.h \
		src/Eigen/src/Eigenvalues/ComplexSchur_MKL.h \
		src/Eigen/src/Eigenvalues/SelfAdjointEigenSolver_MKL.h \
		src/JacobianPseudoIK.hpp \
		src/FABRIK.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/IKWidget.o src/IKWidget.cpp

.obj/Joint.o: src/Joint.cpp src/Joint.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/Joint.o src/Joint.cpp

.obj/KinematicChain.o: src/KinematicChain.cpp src/KinematicChain.hpp \
		src/Joint.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/KinematicChain.o src/KinematicChain.cpp

.obj/Window.o: src/Window.cpp src/Window.hpp \
		src/IKWidget.hpp \
		src/KinematicChain.hpp \
		src/Joint.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/Window.o src/Window.cpp

.obj/AnalyticIK.o: src/AnalyticIK.cpp src/AnalyticIK.hpp \
		src/KinematicChain.hpp \
		src/Joint.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/AnalyticIK.o src/AnalyticIK.cpp

.obj/JacobianIK.o: src/JacobianIK.cpp src/JacobianIK.hpp \
		src/KinematicChain.hpp \
		src/Joint.hpp \
		src/Eigen/Dense \
		src/Eigen/Core \
		src/Eigen/src/Core/util/DisableStupidWarnings.h \
		src/Eigen/src/Core/util/Macros.h \
		src/Eigen/src/Core/util/MKL_support.h \
		src/Eigen/src/Core/util/Constants.h \
		src/Eigen/src/Core/util/ForwardDeclarations.h \
		src/Eigen/src/Core/util/Meta.h \
		src/Eigen/src/Core/util/StaticAssert.h \
		src/Eigen/src/Core/util/XprHelper.h \
		src/Eigen/src/Core/util/Memory.h \
		src/Eigen/src/Core/NumTraits.h \
		src/Eigen/src/Core/MathFunctions.h \
		src/Eigen/src/Core/GenericPacketMath.h \
		src/Eigen/src/Core/arch/SSE/PacketMath.h \
		src/Eigen/src/Core/arch/SSE/MathFunctions.h \
		src/Eigen/src/Core/arch/SSE/Complex.h \
		src/Eigen/src/Core/arch/AltiVec/PacketMath.h \
		src/Eigen/src/Core/arch/AltiVec/Complex.h \
		src/Eigen/src/Core/arch/NEON/PacketMath.h \
		src/Eigen/src/Core/arch/NEON/Complex.h \
		src/Eigen/src/Core/arch/Default/Settings.h \
		src/Eigen/src/Core/Functors.h \
		src/Eigen/src/Core/DenseCoeffsBase.h \
		src/Eigen/src/Core/DenseBase.h \
		src/Eigen/src/plugins/BlockMethods.h \
		src/Eigen/src/Core/MatrixBase.h \
		src/Eigen/src/plugins/CommonCwiseUnaryOps.h \
		src/Eigen/src/plugins/CommonCwiseBinaryOps.h \
		src/Eigen/src/plugins/MatrixCwiseUnaryOps.h \
		src/Eigen/src/plugins/MatrixCwiseBinaryOps.h \
		src/Eigen/src/Core/EigenBase.h \
		src/Eigen/src/Core/Assign.h \
		src/Eigen/src/Core/util/BlasUtil.h \
		src/Eigen/src/Core/DenseStorage.h \
		src/Eigen/src/Core/NestByValue.h \
		src/Eigen/src/Core/ForceAlignedAccess.h \
		src/Eigen/src/Core/ReturnByValue.h \
		src/Eigen/src/Core/NoAlias.h \
		src/Eigen/src/Core/PlainObjectBase.h \
		src/Eigen/src/Core/Matrix.h \
		src/Eigen/src/Core/Array.h \
		src/Eigen/src/Core/CwiseBinaryOp.h \
		src/Eigen/src/Core/CwiseUnaryOp.h \
		src/Eigen/src/Core/CwiseNullaryOp.h \
		src/Eigen/src/Core/CwiseUnaryView.h \
		src/Eigen/src/Core/SelfCwiseBinaryOp.h \
		src/Eigen/src/Core/Dot.h \
		src/Eigen/src/Core/StableNorm.h \
		src/Eigen/src/Core/MapBase.h \
		src/Eigen/src/Core/Stride.h \
		src/Eigen/src/Core/Map.h \
		src/Eigen/src/Core/Block.h \
		src/Eigen/src/Core/VectorBlock.h \
		src/Eigen/src/Core/Ref.h \
		src/Eigen/src/Core/Transpose.h \
		src/Eigen/src/Core/DiagonalMatrix.h \
		src/Eigen/src/Core/Diagonal.h \
		src/Eigen/src/Core/DiagonalProduct.h \
		src/Eigen/src/Core/PermutationMatrix.h \
		src/Eigen/src/Core/Transpositions.h \
		src/Eigen/src/Core/Redux.h \
		src/Eigen/src/Core/Visitor.h \
		src/Eigen/src/Core/Fuzzy.h \
		src/Eigen/src/Core/IO.h \
		src/Eigen/src/Core/Swap.h \
		src/Eigen/src/Core/CommaInitializer.h \
		src/Eigen/src/Core/Flagged.h \
		src/Eigen/src/Core/ProductBase.h \
		src/Eigen/src/Core/GeneralProduct.h \
		src/Eigen/src/Core/TriangularMatrix.h \
		src/Eigen/src/Core/SelfAdjointView.h \
		src/Eigen/src/Core/products/GeneralBlockPanelKernel.h \
		src/Eigen/src/Core/products/Parallelizer.h \
		src/Eigen/src/Core/products/CoeffBasedProduct.h \
		src/Eigen/src/Core/products/GeneralMatrixVector.h \
		src/Eigen/src/Core/products/GeneralMatrixMatrix.h \
		src/Eigen/src/Core/SolveTriangular.h \
		src/Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
		src/Eigen/src/Core/products/SelfadjointMatrixVector.h \
		src/Eigen/src/Core/products/SelfadjointMatrixMatrix.h \
		src/Eigen/src/Core/products/SelfadjointProduct.h \
		src/Eigen/src/Core/products/SelfadjointRank2Update.h \
		src/Eigen/src/Core/products/TriangularMatrixVector.h \
		src/Eigen/src/Core/products/TriangularMatrixMatrix.h \
		src/Eigen/src/Core/products/TriangularSolverMatrix.h \
		src/Eigen/src/Core/products/TriangularSolverVector.h \
		src/Eigen/src/Core/BandMatrix.h \
		src/Eigen/src/Core/CoreIterators.h \
		src/Eigen/src/Core/BooleanRedux.h \
		src/Eigen/src/Core/Select.h \
		src/Eigen/src/Core/VectorwiseOp.h \
		src/Eigen/src/Core/Random.h \
		src/Eigen/src/Core/Replicate.h \
		src/Eigen/src/Core/Reverse.h \
		src/Eigen/src/Core/ArrayBase.h \
		src/Eigen/src/plugins/ArrayCwiseUnaryOps.h \
		src/Eigen/src/plugins/ArrayCwiseBinaryOps.h \
		src/Eigen/src/Core/ArrayWrapper.h \
		src/Eigen/src/Core/products/GeneralMatrixMatrix_MKL.h \
		src/Eigen/src/Core/products/GeneralMatrixVector_MKL.h \
		src/Eigen/src/Core/products/GeneralMatrixMatrixTriangular_MKL.h \
		src/Eigen/src/Core/products/SelfadjointMatrixMatrix_MKL.h \
		src/Eigen/src/Core/products/SelfadjointMatrixVector_MKL.h \
		src/Eigen/src/Core/products/TriangularMatrixMatrix_MKL.h \
		src/Eigen/src/Core/products/TriangularMatrixVector_MKL.h \
		src/Eigen/src/Core/products/TriangularSolverMatrix_MKL.h \
		src/Eigen/src/Core/Assign_MKL.h \
		src/Eigen/src/Core/GlobalFunctions.h \
		src/Eigen/src/Core/util/ReenableStupidWarnings.h \
		src/Eigen/Eigen2Support \
		src/Eigen/src/Eigen2Support/Macros.h \
		src/Eigen/src/Eigen2Support/Memory.h \
		src/Eigen/src/Eigen2Support/Meta.h \
		src/Eigen/src/Eigen2Support/Lazy.h \
		src/Eigen/src/Eigen2Support/Cwise.h \
		src/Eigen/src/Eigen2Support/CwiseOperators.h \
		src/Eigen/src/Eigen2Support/TriangularSolver.h \
		src/Eigen/src/Eigen2Support/Block.h \
		src/Eigen/src/Eigen2Support/VectorBlock.h \
		src/Eigen/src/Eigen2Support/Minor.h \
		src/Eigen/src/Eigen2Support/MathFunctions.h \
		src/Eigen/LU \
		src/Eigen/src/misc/Solve.h \
		src/Eigen/src/misc/Kernel.h \
		src/Eigen/src/misc/Image.h \
		src/Eigen/src/LU/FullPivLU.h \
		src/Eigen/src/LU/PartialPivLU.h \
		src/Eigen/src/LU/PartialPivLU_MKL.h \
		src/Eigen/src/LU/Determinant.h \
		src/Eigen/src/LU/Inverse.h \
		src/Eigen/src/LU/arch/Inverse_SSE.h \
		src/Eigen/src/Eigen2Support/LU.h \
		src/Eigen/Cholesky \
		src/Eigen/src/Cholesky/LLT.h \
		src/Eigen/src/Cholesky/LDLT.h \
		src/Eigen/src/Cholesky/LLT_MKL.h \
		src/Eigen/QR \
		src/Eigen/Jacobi \
		src/Eigen/src/Jacobi/Jacobi.h \
		src/Eigen/Householder \
		src/Eigen/src/Householder/Householder.h \
		src/Eigen/src/Householder/HouseholderSequence.h \
		src/Eigen/src/Householder/BlockHouseholder.h \
		src/Eigen/src/QR/HouseholderQR.h \
		src/Eigen/src/QR/FullPivHouseholderQR.h \
		src/Eigen/src/QR/ColPivHouseholderQR.h \
		src/Eigen/src/QR/HouseholderQR_MKL.h \
		src/Eigen/src/QR/ColPivHouseholderQR_MKL.h \
		src/Eigen/src/Eigen2Support/QR.h \
		src/Eigen/Eigenvalues \
		src/Eigen/Geometry \
		src/Eigen/SVD \
		src/Eigen/src/SVD/JacobiSVD.h \
		src/Eigen/src/SVD/JacobiSVD_MKL.h \
		src/Eigen/src/SVD/UpperBidiagonalization.h \
		src/Eigen/src/Eigen2Support/SVD.h \
		src/Eigen/src/Geometry/OrthoMethods.h \
		src/Eigen/src/Geometry/EulerAngles.h \
		src/Eigen/src/Geometry/Homogeneous.h \
		src/Eigen/src/Geometry/RotationBase.h \
		src/Eigen/src/Geometry/Rotation2D.h \
		src/Eigen/src/Geometry/Quaternion.h \
		src/Eigen/src/Geometry/AngleAxis.h \
		src/Eigen/src/Geometry/Transform.h \
		src/Eigen/src/Geometry/Translation.h \
		src/Eigen/src/Geometry/Scaling.h \
		src/Eigen/src/Geometry/Hyperplane.h \
		src/Eigen/src/Geometry/ParametrizedLine.h \
		src/Eigen/src/Geometry/AlignedBox.h \
		src/Eigen/src/Geometry/Umeyama.h \
		src/Eigen/src/Geometry/arch/Geometry_SSE.h \
		src/Eigen/src/Eigen2Support/Geometry/All.h \
		src/Eigen/src/Eigen2Support/Geometry/RotationBase.h \
		src/Eigen/src/Eigen2Support/Geometry/Rotation2D.h \
		src/Eigen/src/Eigen2Support/Geometry/Quaternion.h \
		src/Eigen/src/Eigen2Support/Geometry/AngleAxis.h \
		src/Eigen/src/Eigen2Support/Geometry/Transform.h \
		src/Eigen/src/Eigen2Support/Geometry/Translation.h \
		src/Eigen/src/Eigen2Support/Geometry/Scaling.h \
		src/Eigen/src/Eigen2Support/Geometry/AlignedBox.h \
		src/Eigen/src/Eigen2Support/Geometry/Hyperplane.h \
		src/Eigen/src/Eigen2Support/Geometry/ParametrizedLine.h \
		src/Eigen/src/Eigenvalues/Tridiagonalization.h \
		src/Eigen/src/Eigenvalues/RealSchur.h \
		src/Eigen/src/Eigenvalues/HessenbergDecomposition.h \
		src/Eigen/src/Eigenvalues/EigenSolver.h \
		src/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h \
		src/Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h \
		src/Eigen/src/Eigenvalues/ComplexSchur.h \
		src/Eigen/src/Eigenvalues/ComplexEigenSolver.h \
		src/Eigen/src/Eigenvalues/RealQZ.h \
		src/Eigen/src/Eigenvalues/GeneralizedEigenSolver.h \
		src/Eigen/src/Eigenvalues/MatrixBaseEigenvalues.h \
		src/Eigen/src/Eigenvalues/RealSchur_MKL.h \
		src/Eigen/src/Eigenvalues/ComplexSchur_MKL.h \
		src/Eigen/src/Eigenvalues/SelfAdjointEigenSolver_MKL.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/JacobianIK.o src/JacobianIK.cpp

.obj/JacobianPseudoIK.o: src/JacobianPseudoIK.cpp src/JacobianPseudoIK.hpp \
		src/KinematicChain.hpp \
		src/Joint.hpp \
		src/Eigen/Dense \
		src/Eigen/Core \
		src/Eigen/src/Core/util/DisableStupidWarnings.h \
		src/Eigen/src/Core/util/Macros.h \
		src/Eigen/src/Core/util/MKL_support.h \
		src/Eigen/src/Core/util/Constants.h \
		src/Eigen/src/Core/util/ForwardDeclarations.h \
		src/Eigen/src/Core/util/Meta.h \
		src/Eigen/src/Core/util/StaticAssert.h \
		src/Eigen/src/Core/util/XprHelper.h \
		src/Eigen/src/Core/util/Memory.h \
		src/Eigen/src/Core/NumTraits.h \
		src/Eigen/src/Core/MathFunctions.h \
		src/Eigen/src/Core/GenericPacketMath.h \
		src/Eigen/src/Core/arch/SSE/PacketMath.h \
		src/Eigen/src/Core/arch/SSE/MathFunctions.h \
		src/Eigen/src/Core/arch/SSE/Complex.h \
		src/Eigen/src/Core/arch/AltiVec/PacketMath.h \
		src/Eigen/src/Core/arch/AltiVec/Complex.h \
		src/Eigen/src/Core/arch/NEON/PacketMath.h \
		src/Eigen/src/Core/arch/NEON/Complex.h \
		src/Eigen/src/Core/arch/Default/Settings.h \
		src/Eigen/src/Core/Functors.h \
		src/Eigen/src/Core/DenseCoeffsBase.h \
		src/Eigen/src/Core/DenseBase.h \
		src/Eigen/src/plugins/BlockMethods.h \
		src/Eigen/src/Core/MatrixBase.h \
		src/Eigen/src/plugins/CommonCwiseUnaryOps.h \
		src/Eigen/src/plugins/CommonCwiseBinaryOps.h \
		src/Eigen/src/plugins/MatrixCwiseUnaryOps.h \
		src/Eigen/src/plugins/MatrixCwiseBinaryOps.h \
		src/Eigen/src/Core/EigenBase.h \
		src/Eigen/src/Core/Assign.h \
		src/Eigen/src/Core/util/BlasUtil.h \
		src/Eigen/src/Core/DenseStorage.h \
		src/Eigen/src/Core/NestByValue.h \
		src/Eigen/src/Core/ForceAlignedAccess.h \
		src/Eigen/src/Core/ReturnByValue.h \
		src/Eigen/src/Core/NoAlias.h \
		src/Eigen/src/Core/PlainObjectBase.h \
		src/Eigen/src/Core/Matrix.h \
		src/Eigen/src/Core/Array.h \
		src/Eigen/src/Core/CwiseBinaryOp.h \
		src/Eigen/src/Core/CwiseUnaryOp.h \
		src/Eigen/src/Core/CwiseNullaryOp.h \
		src/Eigen/src/Core/CwiseUnaryView.h \
		src/Eigen/src/Core/SelfCwiseBinaryOp.h \
		src/Eigen/src/Core/Dot.h \
		src/Eigen/src/Core/StableNorm.h \
		src/Eigen/src/Core/MapBase.h \
		src/Eigen/src/Core/Stride.h \
		src/Eigen/src/Core/Map.h \
		src/Eigen/src/Core/Block.h \
		src/Eigen/src/Core/VectorBlock.h \
		src/Eigen/src/Core/Ref.h \
		src/Eigen/src/Core/Transpose.h \
		src/Eigen/src/Core/DiagonalMatrix.h \
		src/Eigen/src/Core/Diagonal.h \
		src/Eigen/src/Core/DiagonalProduct.h \
		src/Eigen/src/Core/PermutationMatrix.h \
		src/Eigen/src/Core/Transpositions.h \
		src/Eigen/src/Core/Redux.h \
		src/Eigen/src/Core/Visitor.h \
		src/Eigen/src/Core/Fuzzy.h \
		src/Eigen/src/Core/IO.h \
		src/Eigen/src/Core/Swap.h \
		src/Eigen/src/Core/CommaInitializer.h \
		src/Eigen/src/Core/Flagged.h \
		src/Eigen/src/Core/ProductBase.h \
		src/Eigen/src/Core/GeneralProduct.h \
		src/Eigen/src/Core/TriangularMatrix.h \
		src/Eigen/src/Core/SelfAdjointView.h \
		src/Eigen/src/Core/products/GeneralBlockPanelKernel.h \
		src/Eigen/src/Core/products/Parallelizer.h \
		src/Eigen/src/Core/products/CoeffBasedProduct.h \
		src/Eigen/src/Core/products/GeneralMatrixVector.h \
		src/Eigen/src/Core/products/GeneralMatrixMatrix.h \
		src/Eigen/src/Core/SolveTriangular.h \
		src/Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
		src/Eigen/src/Core/products/SelfadjointMatrixVector.h \
		src/Eigen/src/Core/products/SelfadjointMatrixMatrix.h \
		src/Eigen/src/Core/products/SelfadjointProduct.h \
		src/Eigen/src/Core/products/SelfadjointRank2Update.h \
		src/Eigen/src/Core/products/TriangularMatrixVector.h \
		src/Eigen/src/Core/products/TriangularMatrixMatrix.h \
		src/Eigen/src/Core/products/TriangularSolverMatrix.h \
		src/Eigen/src/Core/products/TriangularSolverVector.h \
		src/Eigen/src/Core/BandMatrix.h \
		src/Eigen/src/Core/CoreIterators.h \
		src/Eigen/src/Core/BooleanRedux.h \
		src/Eigen/src/Core/Select.h \
		src/Eigen/src/Core/VectorwiseOp.h \
		src/Eigen/src/Core/Random.h \
		src/Eigen/src/Core/Replicate.h \
		src/Eigen/src/Core/Reverse.h \
		src/Eigen/src/Core/ArrayBase.h \
		src/Eigen/src/plugins/ArrayCwiseUnaryOps.h \
		src/Eigen/src/plugins/ArrayCwiseBinaryOps.h \
		src/Eigen/src/Core/ArrayWrapper.h \
		src/Eigen/src/Core/products/GeneralMatrixMatrix_MKL.h \
		src/Eigen/src/Core/products/GeneralMatrixVector_MKL.h \
		src/Eigen/src/Core/products/GeneralMatrixMatrixTriangular_MKL.h \
		src/Eigen/src/Core/products/SelfadjointMatrixMatrix_MKL.h \
		src/Eigen/src/Core/products/SelfadjointMatrixVector_MKL.h \
		src/Eigen/src/Core/products/TriangularMatrixMatrix_MKL.h \
		src/Eigen/src/Core/products/TriangularMatrixVector_MKL.h \
		src/Eigen/src/Core/products/TriangularSolverMatrix_MKL.h \
		src/Eigen/src/Core/Assign_MKL.h \
		src/Eigen/src/Core/GlobalFunctions.h \
		src/Eigen/src/Core/util/ReenableStupidWarnings.h \
		src/Eigen/Eigen2Support \
		src/Eigen/src/Eigen2Support/Macros.h \
		src/Eigen/src/Eigen2Support/Memory.h \
		src/Eigen/src/Eigen2Support/Meta.h \
		src/Eigen/src/Eigen2Support/Lazy.h \
		src/Eigen/src/Eigen2Support/Cwise.h \
		src/Eigen/src/Eigen2Support/CwiseOperators.h \
		src/Eigen/src/Eigen2Support/TriangularSolver.h \
		src/Eigen/src/Eigen2Support/Block.h \
		src/Eigen/src/Eigen2Support/VectorBlock.h \
		src/Eigen/src/Eigen2Support/Minor.h \
		src/Eigen/src/Eigen2Support/MathFunctions.h \
		src/Eigen/LU \
		src/Eigen/src/misc/Solve.h \
		src/Eigen/src/misc/Kernel.h \
		src/Eigen/src/misc/Image.h \
		src/Eigen/src/LU/FullPivLU.h \
		src/Eigen/src/LU/PartialPivLU.h \
		src/Eigen/src/LU/PartialPivLU_MKL.h \
		src/Eigen/src/LU/Determinant.h \
		src/Eigen/src/LU/Inverse.h \
		src/Eigen/src/LU/arch/Inverse_SSE.h \
		src/Eigen/src/Eigen2Support/LU.h \
		src/Eigen/Cholesky \
		src/Eigen/src/Cholesky/LLT.h \
		src/Eigen/src/Cholesky/LDLT.h \
		src/Eigen/src/Cholesky/LLT_MKL.h \
		src/Eigen/QR \
		src/Eigen/Jacobi \
		src/Eigen/src/Jacobi/Jacobi.h \
		src/Eigen/Householder \
		src/Eigen/src/Householder/Householder.h \
		src/Eigen/src/Householder/HouseholderSequence.h \
		src/Eigen/src/Householder/BlockHouseholder.h \
		src/Eigen/src/QR/HouseholderQR.h \
		src/Eigen/src/QR/FullPivHouseholderQR.h \
		src/Eigen/src/QR/ColPivHouseholderQR.h \
		src/Eigen/src/QR/HouseholderQR_MKL.h \
		src/Eigen/src/QR/ColPivHouseholderQR_MKL.h \
		src/Eigen/src/Eigen2Support/QR.h \
		src/Eigen/Eigenvalues \
		src/Eigen/Geometry \
		src/Eigen/SVD \
		src/Eigen/src/SVD/JacobiSVD.h \
		src/Eigen/src/SVD/JacobiSVD_MKL.h \
		src/Eigen/src/SVD/UpperBidiagonalization.h \
		src/Eigen/src/Eigen2Support/SVD.h \
		src/Eigen/src/Geometry/OrthoMethods.h \
		src/Eigen/src/Geometry/EulerAngles.h \
		src/Eigen/src/Geometry/Homogeneous.h \
		src/Eigen/src/Geometry/RotationBase.h \
		src/Eigen/src/Geometry/Rotation2D.h \
		src/Eigen/src/Geometry/Quaternion.h \
		src/Eigen/src/Geometry/AngleAxis.h \
		src/Eigen/src/Geometry/Transform.h \
		src/Eigen/src/Geometry/Translation.h \
		src/Eigen/src/Geometry/Scaling.h \
		src/Eigen/src/Geometry/Hyperplane.h \
		src/Eigen/src/Geometry/ParametrizedLine.h \
		src/Eigen/src/Geometry/AlignedBox.h \
		src/Eigen/src/Geometry/Umeyama.h \
		src/Eigen/src/Geometry/arch/Geometry_SSE.h \
		src/Eigen/src/Eigen2Support/Geometry/All.h \
		src/Eigen/src/Eigen2Support/Geometry/RotationBase.h \
		src/Eigen/src/Eigen2Support/Geometry/Rotation2D.h \
		src/Eigen/src/Eigen2Support/Geometry/Quaternion.h \
		src/Eigen/src/Eigen2Support/Geometry/AngleAxis.h \
		src/Eigen/src/Eigen2Support/Geometry/Transform.h \
		src/Eigen/src/Eigen2Support/Geometry/Translation.h \
		src/Eigen/src/Eigen2Support/Geometry/Scaling.h \
		src/Eigen/src/Eigen2Support/Geometry/AlignedBox.h \
		src/Eigen/src/Eigen2Support/Geometry/Hyperplane.h \
		src/Eigen/src/Eigen2Support/Geometry/ParametrizedLine.h \
		src/Eigen/src/Eigenvalues/Tridiagonalization.h \
		src/Eigen/src/Eigenvalues/RealSchur.h \
		src/Eigen/src/Eigenvalues/HessenbergDecomposition.h \
		src/Eigen/src/Eigenvalues/EigenSolver.h \
		src/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h \
		src/Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h \
		src/Eigen/src/Eigenvalues/ComplexSchur.h \
		src/Eigen/src/Eigenvalues/ComplexEigenSolver.h \
		src/Eigen/src/Eigenvalues/RealQZ.h \
		src/Eigen/src/Eigenvalues/GeneralizedEigenSolver.h \
		src/Eigen/src/Eigenvalues/MatrixBaseEigenvalues.h \
		src/Eigen/src/Eigenvalues/RealSchur_MKL.h \
		src/Eigen/src/Eigenvalues/ComplexSchur_MKL.h \
		src/Eigen/src/Eigenvalues/SelfAdjointEigenSolver_MKL.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/JacobianPseudoIK.o src/JacobianPseudoIK.cpp

.obj/FABRIK.o: src/FABRIK.cpp src/FABRIK.hpp \
		src/KinematicChain.hpp \
		src/Joint.hpp \
		src/Eigen/Dense \
		src/Eigen/Core \
		src/Eigen/src/Core/util/DisableStupidWarnings.h \
		src/Eigen/src/Core/util/Macros.h \
		src/Eigen/src/Core/util/MKL_support.h \
		src/Eigen/src/Core/util/Constants.h \
		src/Eigen/src/Core/util/ForwardDeclarations.h \
		src/Eigen/src/Core/util/Meta.h \
		src/Eigen/src/Core/util/StaticAssert.h \
		src/Eigen/src/Core/util/XprHelper.h \
		src/Eigen/src/Core/util/Memory.h \
		src/Eigen/src/Core/NumTraits.h \
		src/Eigen/src/Core/MathFunctions.h \
		src/Eigen/src/Core/GenericPacketMath.h \
		src/Eigen/src/Core/arch/SSE/PacketMath.h \
		src/Eigen/src/Core/arch/SSE/MathFunctions.h \
		src/Eigen/src/Core/arch/SSE/Complex.h \
		src/Eigen/src/Core/arch/AltiVec/PacketMath.h \
		src/Eigen/src/Core/arch/AltiVec/Complex.h \
		src/Eigen/src/Core/arch/NEON/PacketMath.h \
		src/Eigen/src/Core/arch/NEON/Complex.h \
		src/Eigen/src/Core/arch/Default/Settings.h \
		src/Eigen/src/Core/Functors.h \
		src/Eigen/src/Core/DenseCoeffsBase.h \
		src/Eigen/src/Core/DenseBase.h \
		src/Eigen/src/plugins/BlockMethods.h \
		src/Eigen/src/Core/MatrixBase.h \
		src/Eigen/src/plugins/CommonCwiseUnaryOps.h \
		src/Eigen/src/plugins/CommonCwiseBinaryOps.h \
		src/Eigen/src/plugins/MatrixCwiseUnaryOps.h \
		src/Eigen/src/plugins/MatrixCwiseBinaryOps.h \
		src/Eigen/src/Core/EigenBase.h \
		src/Eigen/src/Core/Assign.h \
		src/Eigen/src/Core/util/BlasUtil.h \
		src/Eigen/src/Core/DenseStorage.h \
		src/Eigen/src/Core/NestByValue.h \
		src/Eigen/src/Core/ForceAlignedAccess.h \
		src/Eigen/src/Core/ReturnByValue.h \
		src/Eigen/src/Core/NoAlias.h \
		src/Eigen/src/Core/PlainObjectBase.h \
		src/Eigen/src/Core/Matrix.h \
		src/Eigen/src/Core/Array.h \
		src/Eigen/src/Core/CwiseBinaryOp.h \
		src/Eigen/src/Core/CwiseUnaryOp.h \
		src/Eigen/src/Core/CwiseNullaryOp.h \
		src/Eigen/src/Core/CwiseUnaryView.h \
		src/Eigen/src/Core/SelfCwiseBinaryOp.h \
		src/Eigen/src/Core/Dot.h \
		src/Eigen/src/Core/StableNorm.h \
		src/Eigen/src/Core/MapBase.h \
		src/Eigen/src/Core/Stride.h \
		src/Eigen/src/Core/Map.h \
		src/Eigen/src/Core/Block.h \
		src/Eigen/src/Core/VectorBlock.h \
		src/Eigen/src/Core/Ref.h \
		src/Eigen/src/Core/Transpose.h \
		src/Eigen/src/Core/DiagonalMatrix.h \
		src/Eigen/src/Core/Diagonal.h \
		src/Eigen/src/Core/DiagonalProduct.h \
		src/Eigen/src/Core/PermutationMatrix.h \
		src/Eigen/src/Core/Transpositions.h \
		src/Eigen/src/Core/Redux.h \
		src/Eigen/src/Core/Visitor.h \
		src/Eigen/src/Core/Fuzzy.h \
		src/Eigen/src/Core/IO.h \
		src/Eigen/src/Core/Swap.h \
		src/Eigen/src/Core/CommaInitializer.h \
		src/Eigen/src/Core/Flagged.h \
		src/Eigen/src/Core/ProductBase.h \
		src/Eigen/src/Core/GeneralProduct.h \
		src/Eigen/src/Core/TriangularMatrix.h \
		src/Eigen/src/Core/SelfAdjointView.h \
		src/Eigen/src/Core/products/GeneralBlockPanelKernel.h \
		src/Eigen/src/Core/products/Parallelizer.h \
		src/Eigen/src/Core/products/CoeffBasedProduct.h \
		src/Eigen/src/Core/products/GeneralMatrixVector.h \
		src/Eigen/src/Core/products/GeneralMatrixMatrix.h \
		src/Eigen/src/Core/SolveTriangular.h \
		src/Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
		src/Eigen/src/Core/products/SelfadjointMatrixVector.h \
		src/Eigen/src/Core/products/SelfadjointMatrixMatrix.h \
		src/Eigen/src/Core/products/SelfadjointProduct.h \
		src/Eigen/src/Core/products/SelfadjointRank2Update.h \
		src/Eigen/src/Core/products/TriangularMatrixVector.h \
		src/Eigen/src/Core/products/TriangularMatrixMatrix.h \
		src/Eigen/src/Core/products/TriangularSolverMatrix.h \
		src/Eigen/src/Core/products/TriangularSolverVector.h \
		src/Eigen/src/Core/BandMatrix.h \
		src/Eigen/src/Core/CoreIterators.h \
		src/Eigen/src/Core/BooleanRedux.h \
		src/Eigen/src/Core/Select.h \
		src/Eigen/src/Core/VectorwiseOp.h \
		src/Eigen/src/Core/Random.h \
		src/Eigen/src/Core/Replicate.h \
		src/Eigen/src/Core/Reverse.h \
		src/Eigen/src/Core/ArrayBase.h \
		src/Eigen/src/plugins/ArrayCwiseUnaryOps.h \
		src/Eigen/src/plugins/ArrayCwiseBinaryOps.h \
		src/Eigen/src/Core/ArrayWrapper.h \
		src/Eigen/src/Core/products/GeneralMatrixMatrix_MKL.h \
		src/Eigen/src/Core/products/GeneralMatrixVector_MKL.h \
		src/Eigen/src/Core/products/GeneralMatrixMatrixTriangular_MKL.h \
		src/Eigen/src/Core/products/SelfadjointMatrixMatrix_MKL.h \
		src/Eigen/src/Core/products/SelfadjointMatrixVector_MKL.h \
		src/Eigen/src/Core/products/TriangularMatrixMatrix_MKL.h \
		src/Eigen/src/Core/products/TriangularMatrixVector_MKL.h \
		src/Eigen/src/Core/products/TriangularSolverMatrix_MKL.h \
		src/Eigen/src/Core/Assign_MKL.h \
		src/Eigen/src/Core/GlobalFunctions.h \
		src/Eigen/src/Core/util/ReenableStupidWarnings.h \
		src/Eigen/Eigen2Support \
		src/Eigen/src/Eigen2Support/Macros.h \
		src/Eigen/src/Eigen2Support/Memory.h \
		src/Eigen/src/Eigen2Support/Meta.h \
		src/Eigen/src/Eigen2Support/Lazy.h \
		src/Eigen/src/Eigen2Support/Cwise.h \
		src/Eigen/src/Eigen2Support/CwiseOperators.h \
		src/Eigen/src/Eigen2Support/TriangularSolver.h \
		src/Eigen/src/Eigen2Support/Block.h \
		src/Eigen/src/Eigen2Support/VectorBlock.h \
		src/Eigen/src/Eigen2Support/Minor.h \
		src/Eigen/src/Eigen2Support/MathFunctions.h \
		src/Eigen/LU \
		src/Eigen/src/misc/Solve.h \
		src/Eigen/src/misc/Kernel.h \
		src/Eigen/src/misc/Image.h \
		src/Eigen/src/LU/FullPivLU.h \
		src/Eigen/src/LU/PartialPivLU.h \
		src/Eigen/src/LU/PartialPivLU_MKL.h \
		src/Eigen/src/LU/Determinant.h \
		src/Eigen/src/LU/Inverse.h \
		src/Eigen/src/LU/arch/Inverse_SSE.h \
		src/Eigen/src/Eigen2Support/LU.h \
		src/Eigen/Cholesky \
		src/Eigen/src/Cholesky/LLT.h \
		src/Eigen/src/Cholesky/LDLT.h \
		src/Eigen/src/Cholesky/LLT_MKL.h \
		src/Eigen/QR \
		src/Eigen/Jacobi \
		src/Eigen/src/Jacobi/Jacobi.h \
		src/Eigen/Householder \
		src/Eigen/src/Householder/Householder.h \
		src/Eigen/src/Householder/HouseholderSequence.h \
		src/Eigen/src/Householder/BlockHouseholder.h \
		src/Eigen/src/QR/HouseholderQR.h \
		src/Eigen/src/QR/FullPivHouseholderQR.h \
		src/Eigen/src/QR/ColPivHouseholderQR.h \
		src/Eigen/src/QR/HouseholderQR_MKL.h \
		src/Eigen/src/QR/ColPivHouseholderQR_MKL.h \
		src/Eigen/src/Eigen2Support/QR.h \
		src/Eigen/Eigenvalues \
		src/Eigen/Geometry \
		src/Eigen/SVD \
		src/Eigen/src/SVD/JacobiSVD.h \
		src/Eigen/src/SVD/JacobiSVD_MKL.h \
		src/Eigen/src/SVD/UpperBidiagonalization.h \
		src/Eigen/src/Eigen2Support/SVD.h \
		src/Eigen/src/Geometry/OrthoMethods.h \
		src/Eigen/src/Geometry/EulerAngles.h \
		src/Eigen/src/Geometry/Homogeneous.h \
		src/Eigen/src/Geometry/RotationBase.h \
		src/Eigen/src/Geometry/Rotation2D.h \
		src/Eigen/src/Geometry/Quaternion.h \
		src/Eigen/src/Geometry/AngleAxis.h \
		src/Eigen/src/Geometry/Transform.h \
		src/Eigen/src/Geometry/Translation.h \
		src/Eigen/src/Geometry/Scaling.h \
		src/Eigen/src/Geometry/Hyperplane.h \
		src/Eigen/src/Geometry/ParametrizedLine.h \
		src/Eigen/src/Geometry/AlignedBox.h \
		src/Eigen/src/Geometry/Umeyama.h \
		src/Eigen/src/Geometry/arch/Geometry_SSE.h \
		src/Eigen/src/Eigen2Support/Geometry/All.h \
		src/Eigen/src/Eigen2Support/Geometry/RotationBase.h \
		src/Eigen/src/Eigen2Support/Geometry/Rotation2D.h \
		src/Eigen/src/Eigen2Support/Geometry/Quaternion.h \
		src/Eigen/src/Eigen2Support/Geometry/AngleAxis.h \
		src/Eigen/src/Eigen2Support/Geometry/Transform.h \
		src/Eigen/src/Eigen2Support/Geometry/Translation.h \
		src/Eigen/src/Eigen2Support/Geometry/Scaling.h \
		src/Eigen/src/Eigen2Support/Geometry/AlignedBox.h \
		src/Eigen/src/Eigen2Support/Geometry/Hyperplane.h \
		src/Eigen/src/Eigen2Support/Geometry/ParametrizedLine.h \
		src/Eigen/src/Eigenvalues/Tridiagonalization.h \
		src/Eigen/src/Eigenvalues/RealSchur.h \
		src/Eigen/src/Eigenvalues/HessenbergDecomposition.h \
		src/Eigen/src/Eigenvalues/EigenSolver.h \
		src/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h \
		src/Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h \
		src/Eigen/src/Eigenvalues/ComplexSchur.h \
		src/Eigen/src/Eigenvalues/ComplexEigenSolver.h \
		src/Eigen/src/Eigenvalues/RealQZ.h \
		src/Eigen/src/Eigenvalues/GeneralizedEigenSolver.h \
		src/Eigen/src/Eigenvalues/MatrixBaseEigenvalues.h \
		src/Eigen/src/Eigenvalues/RealSchur_MKL.h \
		src/Eigen/src/Eigenvalues/ComplexSchur_MKL.h \
		src/Eigen/src/Eigenvalues/SelfAdjointEigenSolver_MKL.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/FABRIK.o src/FABRIK.cpp

.obj/moc_IKWidget.o: .moc/moc_IKWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_IKWidget.o .moc/moc_IKWidget.cpp

.obj/moc_Window.o: .moc/moc_Window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_Window.o .moc/moc_Window.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

